-- Request item editing audit trail and inventory batch idempotency.
-- Apply once to an existing PostgreSQL deployment before starting the new app.
-- The statements are repeatable and intentionally do not alter existing data.

CREATE TABLE IF NOT EXISTS request_item_audits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES requests(id) ON DELETE CASCADE,
    request_item_id INTEGER REFERENCES request_items(id) ON DELETE SET NULL,
    operator_id INTEGER NOT NULL REFERENCES users(id),
    action VARCHAR(30) NOT NULL,
    before_json TEXT,
    after_json TEXT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_request_item_audits_request_id
    ON request_item_audits(request_id);
CREATE INDEX IF NOT EXISTS ix_request_item_audits_request_item_id
    ON request_item_audits(request_item_id);
CREATE INDEX IF NOT EXISTS ix_request_item_audits_operator_id
    ON request_item_audits(operator_id);
CREATE INDEX IF NOT EXISTS ix_request_item_audits_create_time
    ON request_item_audits(create_time);

CREATE TABLE IF NOT EXISTS idempotency_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation VARCHAR(50) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    response_json TEXT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_idempotency_operation_key UNIQUE (operation, idempotency_key)
);

CREATE INDEX IF NOT EXISTS ix_idempotency_records_create_time
    ON idempotency_records(create_time);
