-- PR #19 review fixes: preserve archived request-item audits and bind
-- inventory idempotency records to the operator and request payload.
-- Repeatable PostgreSQL migration; it does not delete or rewrite existing data.

CREATE TABLE IF NOT EXISTS request_item_audits_archive (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_id INTEGER NOT NULL REFERENCES requests_archive(id) ON DELETE CASCADE,
    original_request_id INTEGER NOT NULL,
    request_item_id INTEGER,
    operator_id INTEGER REFERENCES users(id),
    action VARCHAR(30) NOT NULL,
    before_json TEXT,
    after_json TEXT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_request_item_audits_archive_archive_id
    ON request_item_audits_archive(archive_id);
CREATE INDEX IF NOT EXISTS ix_request_item_audits_archive_original_request_id
    ON request_item_audits_archive(original_request_id);
CREATE INDEX IF NOT EXISTS ix_request_item_audits_archive_create_time
    ON request_item_audits_archive(create_time);

ALTER TABLE idempotency_records
    ADD COLUMN IF NOT EXISTS operator_id INTEGER REFERENCES users(id);
ALTER TABLE idempotency_records
    ADD COLUMN IF NOT EXISTS request_hash VARCHAR(64);
CREATE INDEX IF NOT EXISTS ix_idempotency_records_operator_id
    ON idempotency_records(operator_id);
CREATE INDEX IF NOT EXISTS ix_idempotency_records_request_hash
    ON idempotency_records(request_hash);
